// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://becmbmgqppbredjvqrbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlY21ibWdxcHBicmVkanZxcmJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MzQ4MjcsImV4cCI6MjA3MjUxMDgyN30.hYWtoNpvVWVo5-kNRWAy2zg0b5ybUL8kA6zI_IsjanU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});